### ISSUE TITLE
[REQUEST] x86 builds

### ISSUE THREAD

**Issue by Keltere** [solidus1983/luci-theme-atmaterial#2]
Hi, sorry to bother but i wanted to know if it's possible to have an x86 build on the release page.
Thanks.

**Comment by solidus1983** [comment]
If your compiling firmware for x86 simply add the following to your feeds.conf

[code]
src-git atmeterial git://github.com/solidus1983/luci-theme-atmaterial.git
[/code]

then run make menu config and make sure its added in luci themes section then save and build again.
